### ISSUE TITLE
Issues with sentence splitting (/delimiter)

### ISSUE THREAD

**Issue by andreicozma1** [Manan-dev/ChatRegex#19]
The current implementation will not properly handle sentences that may end with quotation marks.

There are cases in which sentences may end like "blah blah."

For the fix, we should test it out so that it works properly in all possible cases.

**Comment by andreicozma1** [comment]
Examples:

Note there's also a distinction between " and ” (same for single). Implementation should work for both.
Also let's replace with \n instead of the delimiter, so that it's easier to look at when testing.
That way we know that a single \n delimits sentences, and a double (\n\n) delimits paragraphs.

![image](https://github.com/Manan-dev/ChatRegex/assets/14914491/d13fc8ab-ebe7-445d-982d-49b6b278a05f)

![image](https://github.com/Manan-dev/ChatRegex/assets/14914491/4f7f7f64-cd71-4892-a1db-6dad1c75b06d)

![image](https://github.com/Manan-dev/ChatRegex/assets/14914491/11a97841-ef82-4c3c-82c3-86da6687ce55)

**Comment by zac-perry** [comment]
Do you think you could show me an example of it not working correctly? I may just be misunderstanding what you mean but from my testing, it appears to work. We are wanting to remove the quotes & punctuation, correct? Right now, from what I have tried anyway, it removes all of the punctuation and stop words and appears to be placing the delimiter correctly. 

<img width="846" alt="image" src="https://github.com/Manan-dev/ChatRegex/assets/97002490/e894b918-6613-43bb-8b0e-12eb02d4e350">




Outside of that, I can update it to just use a \n instead of the current delimiter. It is pretty gross to look at currently lol

**Comment by andreicozma1** [comment]
> Do you think you could show me an example of it not working correctly? I may just be misunderstanding what you mean but from my testing, it appears to work. We are wanting to remove the quotes & punctuation, correct? Right now, from what I have tried anyway, it removes all of the punctuation and stop words and appears to be placing the delimiter correctly.
> 
> <img alt="image" width="846" src="https://private-user-images.githubusercontent.com/97002490/272094995-e894b918-6613-43bb-8b0e-12eb02d4e350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTYyODMxNjEsIm5iZiI6MTY5NjI4Mjg2MSwicGF0aCI6Ii85NzAwMjQ5MC8yNzIwOTQ5OTUtZTg5NGI5MTgtNjYxMy00M2JiLThiMGUtMTJlYjAyZDRlMzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMDAyVDIxNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyN2YzYjI4NGFkYTExZjcyNmY5NDUyZTY3MGZhMTdkNWMyM2MyMTMzODQ5ZDA3NTUwNmI3YTEwOWUzY2ZlZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WN-XwrI82JcYh77Sh-LvOF25fXFTVtI9Kjsx7R0QTn8">
> Outside of that, I can update it to just use a \n instead of the current delimiter. It is pretty gross to look at currently lol

Yes, let's do that first and come back to it to re-verify. Though the sentence splitting function should work stand-alone without assuming that anything else is done or will be done outside of it. So don't assume we will be removing punctuation afterwards, and the sentence splitting function should still work.

**Comment by andreicozma1** [comment]
Also we may first want to join paragraphs prior, since they are cut off with newlines mid-sentence.

![image](https://github.com/Manan-dev/ChatRegex/assets/14914491/ad96a5d5-5805-4082-997f-8787388bd67d)

**Comment by zac-perry** [comment]
> > Do you think you could show me an example of it not working correctly? I may just be misunderstanding what you mean but from my testing, it appears to work. We are wanting to remove the quotes & punctuation, correct? Right now, from what I have tried anyway, it removes all of the punctuation and stop words and appears to be placing the delimiter correctly.
> > <img alt="image" width="846" src="https://private-user-images.githubusercontent.com/97002490/272094995-e894b918-6613-43bb-8b0e-12eb02d4e350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTYyODMxNjEsIm5iZiI6MTY5NjI4Mjg2MSwicGF0aCI6Ii85NzAwMjQ5MC8yNzIwOTQ5OTUtZTg5NGI5MTgtNjYxMy00M2JiLThiMGUtMTJlYjAyZDRlMzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMDAyVDIxNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyN2YzYjI4NGFkYTExZjcyNmY5NDUyZTY3MGZhMTdkNWMyM2MyMTMzODQ5ZDA3NTUwNmI3YTEwOWUzY2ZlZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WN-XwrI82JcYh77Sh-LvOF25fXFTVtI9Kjsx7R0QTn8">
> > Outside of that, I can update it to just use a \n instead of the current delimiter. It is pretty gross to look at currently lol
> 
> Yes, let's do that first and come back to it to re-verify. Though the sentence splitting function should work stand-alone without assuming that anything else is done or will be done outside of it. So don't assume we will be removing punctuation afterwards, and the sentence splitting function should still work.

Got it. I'll add in the different potential things that a sentence could end in into the delimiter function.

**Comment by zac-perry** [comment]
@andreicozma1 Think I got it all working and can open a PR momentarily. Just curious, with your recent changes merged, are we also wanting to remove quotes? With the new changes, when running the process data function with the newline as the delimiter, we will have occurrences of a singular line being a quote. for example: 

<img width="906" alt="image" src="https://github.com/Manan-dev/ChatRegex/assets/97002490/2c145a24-1c33-4664-a965-bf20872b9982">

If we do want to keep quotes, I can modify the delimiter function but just wanted to double check. I have the regex to remove the quotes and this is the final form for the formatted data (each line is a sentence)

<img width="844" alt="image" src="https://github.com/Manan-dev/ChatRegex/assets/97002490/ccaabfb6-5740-4bab-ab5c-b81b665d9eb8">

**Comment by andreicozma1** [comment]
hmm, that's interesting. You're right, I guess those must be the Unicode quotes remaining. The previous method to remove punctuation seemed to miss certain symbols, and the downside of the new one is that it only removes ASCII symbols.

Also now that I think about it, since those are unicode quotes and we convert everything to ASCII with the ignore flag when we read the file in, it looks like the Unicode quotes would disappear nonetheless (at least they do seem to disappear on my end)

So maybe let's just assume the text is ASCII-only and there could be an optional ASCII single/double-quote after those end-of-sentence symbols.

So for the final sentence-splitting implementation, maybe something like this would work?
1. first re-join the paragraphs since there's currently random mid-sentence newlines. For this part, maybe this would work (though haven't tested it myself): `re.sub(r"([^\n])\n([^\n])", r"\1 \2", text)` 
2. replace sentence delimiters like you're currently doing, but replacing with a `\n`.
3. split the text by newline to return an array of sentences.

Let me know what you think

**Comment by zac-perry** [comment]
Okay cool, sounds good. Yeah I think that'll work really well. Instead of making a PR just for the newline delimiter stuff, I'll just include that in the PR for the data structure stuff whenever I finish that up. I'll link both issues to that PR if that's cool with you

**Comment by andreicozma1** [comment]
> Okay cool, sounds good. Yeah I think that'll work really well. Instead of making a PR just for the newline delimiter stuff, I'll just include that in the PR for the data structure stuff whenever I finish that up. I'll link both issues to that PR if that's cool with you

sounds good to me!
